### ISSUE TITLE
preg_quote prevents regex from working?

### ISSUE THREAD

**Issue by gopi-ar** [blablacar/nagios-supervisord-processes#1]
Not sure if I'm doing something wrong, but `preg_quote` escapes a regex pattern making it a string, right? Then I can't pass a pattern like `process1|process2` or more complex regexs. 

Is there any reason for this?

**Comment by shtouff** [comment]
Hi 
Do you have a PR that you've tested successfully ?

**Comment by gopi-ar** [comment]
@shtouff I'll make a PR.
